version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true #启动安全
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    restart: always # 服务挂了的时候始终自动重启
    networks:
      es_net-04:
        ipv4_address: "177.178.4.1" #固定ip
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true # 启动安全
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
    restart: always # 服务挂了的时候始终自动重启
    networks:
      es_net-04:
        ipv4_address: "177.178.4.2" #固定ip
 
  kibana01:
    image: docker.elastic.co/kibana/kibana:7.5.0
    container_name: kibana01
    ports:
      - 5602:5601   
    environment:
      - SERVER_NAME=kibana.localhost
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - I18N_LOCALE=zh-CN
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=es_elastic
    depends_on: ['es01']
    links:
      - es01:es
    restart: always # 服务挂了的时候始终自动重启
    networks:
      es_net-04:
        ipv4_address: "177.178.4.3" #固定ip
 
  kibana02:
    image: docker.elastic.co/kibana/kibana:7.5.0
    container_name: kibana02
    ports:
      - 5603:5601   
    environment:
      - SERVER_NAME=kibana.localhost
      - ELASTICSEARCH_HOSTS=http://es02:9200
      - I18N_LOCALE=zh-CN
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=es_elastic
    depends_on: ['es02']
    links:
      - es02:es
    restart: always # 服务挂了的时候始终自动重启
    networks:
      es_net-04:
        ipv4_address: "177.178.4.4" #固定ip
 
volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
 
networks:
  es_net-04:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: "177.178.4.0/16"