version: '3'

services:
  mysql_master:
    container_name: read_replication_demo4_mysql_master
    build: ./mysql
    ports:
      - 3307:3306
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/master/my.cnf:/etc/mysql/my.cnf
      - ./mysql/master/db/:/var/lib/mysql # 低版本的mysql数据存于此
      - ./mysql/master/db-files/:/var/lib/mysql-files # 高版本的mysql数据存于此
      - ./mysql/master.sh:/docker-entrypoint-initdb.d/master.sh #挂载脚本
    restart: always
    networks:
      read_replication_demo4:
        ipv4_address: 177.177.4.2

  mysql_slave1:
    container_name: read_replication_demo4_mysql_slave1
    build: ./mysql
    ports:
      - 3308:3306
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/slave1/my.cnf:/etc/mysql/my.cnf
      - ./mysql/slave1/db/:/var/lib/mysql # 低版本的mysql数据存于此
      - ./mysql/slave1/db-files/:/var/lib/mysql-files # 高版本的mysql数据存于此
      - ./mysql/slave.sh:/docker-entrypoint-initdb.d/slave.sh #挂载脚本
    restart: always
    depends_on:
      - mysql_master
    networks:
      read_replication_demo4:
        ipv4_address: 177.177.4.3

  mysql_slave2:
    container_name: read_replication_demo4_mysql_slave2
    build: ./mysql
    ports:
      - 3309:3306
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/slave2/my.cnf:/etc/mysql/my.cnf
      - ./mysql/slave2/db/:/var/lib/mysql # 低版本的mysql数据存于此
      - ./mysql/slave2/db-files/:/var/lib/mysql-files # 高版本的mysql数据存于此
      - ./mysql/slave.sh:/docker-entrypoint-initdb.d/slave.sh #挂载脚本
    restart: always
    depends_on:
      - mysql_master
    networks:
      read_replication_demo4:
        ipv4_address: 177.177.4.4
  
networks:
  read_replication_demo4:
    driver: bridge
    ipam:
      config:
        - subnet: 177.177.4.0/16
